CREATE TABLE IF NOT EXISTS learning_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,
  wordId INTEGER NOT NULL REFERENCES word(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL,
  result INTEGER,
  timestamp INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS quiz_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,
  wordId INTEGER NOT NULL REFERENCES word(id) ON DELETE CASCADE,
  selected_choice TEXT NOT NULL,
  is_correct INTEGER NOT NULL,
  timestamp INTEGER NOT NULL
);
